### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'gpus'

### ISSUE THREAD

**Issue by TobyZhouWei** [JonasSchult/Mask3D#70]
Hi, I am working to reproduce your excellent work on cloud server. I meet the problems like below:
Traceback (most recent call last):
  File "/root/Mask3D-main/main_instance_segmentation.py", line 99, in main
    test(cfg)
  File "/root/miniconda3/envs/mask3d/lib/python3.9/site-packages/hydra/main.py", line 27, in decorated_main
    return task_function(cfg_passthrough)
  File "/root/Mask3D-main/main_instance_segmentation.py", line 86, in test
    runner = Trainer(
  File "/root/miniconda3/envs/mask3d/lib/python3.9/site-packages/pytorch_lightning/utilities/argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'gpus'.
How can I solve this problems, thank you so much!

**Comment by promesse** [comment]
I met the same problem. How to fix it? Thanks

**Comment by Wang-pengfei** [comment]
> I met the same problem. How to fix it? Thanks

I met the same problem. Did you solve this problem?

**Comment by Wang-pengfei** [comment]
> Hi, I am working to reproduce your excellent work on cloud server. I meet the problems like below: Traceback (most recent call last): File "/root/Mask3D-main/main_instance_segmentation.py", line 99, in main test(cfg) File "/root/miniconda3/envs/mask3d/lib/python3.9/site-packages/hydra/main.py", line 27, in decorated_main return task_function(cfg_passthrough) File "/root/Mask3D-main/main_instance_segmentation.py", line 86, in test runner = Trainer( File "/root/miniconda3/envs/mask3d/lib/python3.9/site-packages/pytorch_lightning/utilities/argparse.py", line 69, in insert_env_defaults return fn(self, **kwargs) TypeError: **init**() got an unexpected keyword argument 'gpus'. How can I solve this problems, thank you so much!

I met the same problem. Did you solve this problem?

**Comment by JonasSchult** [comment]
Hi! :)
Potentially some dependencies do not match.
Try to set up the environment like [this](https://github.com/JonasSchult/Mask3D/pull/51).
Please let me know if it helped.

Best,
Jonas

**Comment by Wang-pengfei** [comment]
Yes，you are right! I soloved this problem by pip install pytorch-lightning==1.7.2

**Comment by promesse** [comment]
> Yes，you are right! I soloved this problem by pip install pytorch-lightning==1.7.2

yes， the same way for me

**Comment by TobyZhouWei** [comment]
Hi, @JonasSchult Could you give me some suggestions about https://github.com/JonasSchult/Mask3D/issues/77. This has bothered me for a long time. Looking forward to your rely. Thank you!!!

**Comment by JonasSchult** [comment]
Hi! :)

Thanks for your interest in our work!

we have just released a [fix](https://github.com/JonasSchult/Mask3D/commit/9f25bf357c97ed7b80402a6233eee8d940c64aeb) which most likely will solve your issue. Just pull the latest version of the project and recreate your virtual python environment following the instructions [here](https://github.com/JonasSchult/Mask3D#dependencies-memo).

Previously, the issue occurred because we did not lock the packages in the Python environment to specific versions. We now made sure that the packages in the environment remain the same.

I will close the issue now. Please feel free to reopen it again if you continue to experience issues.

Best,
Jonas
