### ISSUE TITLE
ModuleNotFoundError: No module named 'MinkowskiEngineBackend'

### ISSUE THREAD

**Issue by bh-cai** [JonasSchult/Mask3D#76]
Thanks for your released the code, but when I run the training by the command: "python main_instance_segmentation.py", I got the following error. I tried to solve the problem through the "https://github.com/NVIDIA/MinkowskiEngine", but I can not find the MinkowskiEngineBackend in this repository, so I ask help for you here. Hoping to hear your reply, thanks a lot!!
![image](https://user-images.githubusercontent.com/58178860/236676126-da7df234-1739-4799-a672-e81d0c7ea583.png)

**Comment by JonasSchult** [comment]
Hi! :)

Thanks for your interest in our work!

we have just released a [fix](https://github.com/JonasSchult/Mask3D/commit/9f25bf357c97ed7b80402a6233eee8d940c64aeb) which most likely will solve your issue. Just pull the latest version of the project and recreate your virtual python environment following the instructions [here](https://github.com/JonasSchult/Mask3D#dependencies-memo).

Previously, the issue occurred because we did not lock the packages in the Python environment to specific versions. We now made sure that the packages in the environment remain the same.

I will close the issue now. Please feel free to reopen it again if you continue to experience issues.

Best,
Jonas
