### ISSUE TITLE
pytorch_lightning.utilities.exceptions.MisconfigurationException: The provided lr scheduler `OneCycleLR` doesn't follow PyTorch's LRScheduler API. You should override the `LightningModule.lr_scheduler_step` hook with your own logic if you are using a custom LR scheduler.

### ISSUE THREAD

**Issue by bh-cai** [JonasSchult/Mask3D#93]
First, thanks for the code you have pubulished.
When I run the command to train the model, I first got the error with "ValueError: not available number labels, select from:
            200, 200" and "
hydra.errors.HydraException: Error calling 'datasets.semseg.SemanticSegmentationDataset' : not available number labels, select from:
            200, 200".
So, I have changed the "num_labels=20" to "num_labels=200" in the config file  "Mask3D\conf\data\indoor.yaml".

However, I got another error with "pytorch_lightning.utilities.exceptions.MisconfigurationException: The provided lr scheduler `OneCycleLR` doesn't follow PyTorch's LRScheduler API. You should override the `LightningModule.lr_scheduler_step` hook with your own logic if you are using a custom LR scheduler."
This error that I can't solve, may get help from you, thank you very much, hope to get your reply.

**Comment by bh-cai** [comment]
@JonasSchult

**Comment by JonasSchult** [comment]
Hi! :)

Thanks for your interest in our work!

we have just released a [fix](https://github.com/JonasSchult/Mask3D/commit/9f25bf357c97ed7b80402a6233eee8d940c64aeb) which most likely will solve your issue. Just pull the latest version of the project and recreate your virtual python environment following the instructions [here](https://github.com/JonasSchult/Mask3D#dependencies-memo).

Previously, the issue occurred because we did not lock the packages in the Python environment to specific versions. We now made sure that the packages in the environment remain the same.

I will close the issue now. Please feel free to reopen it again if you continue to experience issues.

Best,
Jonas

**Comment by bh-cai** [comment]
Thanks for your reply, best wish for you!

Jonas Schult ***@***.***> 于2023年5月31日周三 19:17写道：
