### ISSUE TITLE
Running error on ScanNet

### ISSUE THREAD

**Issue by zhang-zihui** [JonasSchult/Mask3D#97]
Hi, @JonasSchult 
When I processed the ScanNet data and ran script/scannet/scannet_val.sh.
An error occurred as below:

![Screenshot from 2023-06-03 18-13-55](https://github.com/JonasSchult/Mask3D/assets/120791554/be96223b-77cc-46c5-bb77-26e1571184c1)
It seems some errors happened on the "torch_scatter" package?

regards,
zihui

**Comment by JonasSchult** [comment]
Hi! :)

Thanks for your interest in our work!

we have just released a [fix](https://github.com/JonasSchult/Mask3D/commit/9f25bf357c97ed7b80402a6233eee8d940c64aeb) which most likely will solve your issue. Just pull the latest version of the project and recreate your virtual python environment following the instructions [here](https://github.com/JonasSchult/Mask3D#dependencies-memo).

Previously, similar issues occurred because we did not lock the packages in the Python environment to specific versions. We now made sure that the packages in the environment remain the same.

I will close the issue now. Please feel free to reopen it again if you continue to experience issues.

Best,
Jonas
